// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdWTKmK5nt5r_Xr4UEdk2oSPLcsv0i0S0',
    appId: '1:180787258362:web:032a159b56a343297aba43',
    messagingSenderId: '180787258362',
    projectId: 'grup81-ai-jam',
    authDomain: 'grup81-ai-jam.firebaseapp.com',
    storageBucket: 'grup81-ai-jam.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzgqLtilD8EKuz7MKSX7meUCaL9FO5iyk',
    appId: '1:180787258362:android:dfc65f9fab8af9807aba43',
    messagingSenderId: '180787258362',
    projectId: 'grup81-ai-jam',
    storageBucket: 'grup81-ai-jam.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAR8OaaLLDp98jka8FEMsjHprjbD9KaC0c',
    appId: '1:180787258362:ios:bbc49bf8026442727aba43',
    messagingSenderId: '180787258362',
    projectId: 'grup81-ai-jam',
    storageBucket: 'grup81-ai-jam.appspot.com',
    iosBundleId: 'com.example.grup81AiJam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAR8OaaLLDp98jka8FEMsjHprjbD9KaC0c',
    appId: '1:180787258362:ios:bbc49bf8026442727aba43',
    messagingSenderId: '180787258362',
    projectId: 'grup81-ai-jam',
    storageBucket: 'grup81-ai-jam.appspot.com',
    iosBundleId: 'com.example.grup81AiJam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdWTKmK5nt5r_Xr4UEdk2oSPLcsv0i0S0',
    appId: '1:180787258362:web:675c035c0851fea17aba43',
    messagingSenderId: '180787258362',
    projectId: 'grup81-ai-jam',
    authDomain: 'grup81-ai-jam.firebaseapp.com',
    storageBucket: 'grup81-ai-jam.appspot.com',
  );
}
